AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Outputs the time
Resources:
  TimeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs12.x
      CodeUri: ./
      Events:
        HttpRoot:
          Type: Api
          Properties:
            RestApiId: !Ref "MyApiName"
            Path: /TimeResource
            Method: GET

  MyApiName:
    Type: 'AWS::Serverless::Api'
    Properties:
      StageName: prod

Outputs:
  MyApiName:
    Description: "Go to this URL to get the time from the timezone put in index.js"
    Value: !Sub 'https://${MyApiName}.execute-api.${AWS::Region}.amazonaws.com/prod/TimeResource'
